# -*- coding: utf-8 -*-
"""fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXQWElCOK9Y4yCpn_ZiP8G_8DOXRCD9J
"""

import pandas as pd
import numpy as np
import os

# --- CONFIGURATION POUR TOUT AFFICHER SUR UNE SEULE LIGNE ---
pd.set_option('display.max_columns', None)      # Affiche toutes les colonnes
pd.set_option('display.width', 2000)            # Largeur énorme pour éviter le retour à la ligne
pd.set_option('display.max_colwidth', 50)       # Limite un peu la largeur de chaque colonne pour que ça tienne
pd.set_option('display.expand_frame_repr', False) # Interdit à Pandas de couper le tableau en plusieurs blocs

# 1. Définition du chemin d'entrée
path = "jobs_wuzzuf_420.csv"

if not os.path.exists(path):
    print(f"ERREUR : Le fichier '{path}' est introuvable dans {os.getcwd()}")
else:
    df = pd.read_csv(path, encoding='utf-8')

    # --- NETTOYAGE ---
    df.drop_duplicates(subset=['Lien'], inplace=True) if 'Lien' in df.columns else df.drop_duplicates(inplace=True)

    col_titre = 'Titre' if 'Titre' in df.columns else 'Job Title'
    df.dropna(subset=[col_titre], inplace=True)

    df.replace(['N/A', 'n/a', 'None'], np.nan, inplace=True)

    # Note: applymap est remplacé par map dans les versions récentes de Pandas
    df = df.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

    # --- AFFICHAGE ---
    print(f"\nNettoyage terminé : {len(df)} lignes conservées.")
    print("-" * 100)
    print(df.head(420)) # Affiche les 10 premières lignes bien alignées
    print("-" * 100)

    # --- SAUVEGARDE ---
    output_path = "jobs_wuzzuf_420.csv"
    df.to_csv(output_path, index=False, encoding='utf-8-sig')
    print(f"Fichier sauvegardé avec succès sous : {os.path.abspath(output_path)}")

import pandas as pd
import numpy as np
import os

# --- CONFIGURATION POUR TOUT AFFICHER SUR UNE SEULE LIGNE ---
pd.set_option('display.max_columns', None)      # Affiche toutes les colonnes
pd.set_option('display.width', 2000)            # Largeur énorme pour éviter le retour à la ligne
pd.set_option('display.max_colwidth', 50)       # Limite un peu la largeur de chaque colonne pour que ça tienne
pd.set_option('display.expand_frame_repr', False) # Interdit à Pandas de couper le tableau en plusieurs blocs

# 1. Définition du chemin d'entrée
path2 = "jobs_keejob_420.csv"

if not os.path.exists(path2):
    print(f"ERREUR : Le fichier '{path2}' est introuvable dans {os.getcwd()}")
else:
    df2 = pd.read_csv(path2, encoding='utf-8')

    # --- NETTOYAGE ---
    df2.drop_duplicates(subset=['Lien'], inplace=True) if 'Lien' in df2.columns else df2.drop_duplicates(inplace=True)

    col_titre2 = 'Titre' if 'Titre' in df2.columns else 'Job Title'
    df2.dropna(subset=[col_titre2], inplace=True)

    df2.replace(['N/A', 'n/a', 'None'], np.nan, inplace=True)

    # Note: applymap est remplacé par map dans les versions récentes de Pandas
    df2 = df2.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

    # --- AFFICHAGE ---
    print(f"\nNettoyage terminé : {len(df2)} lignes conservées.")
    print("-" * 100)
    print(df2.head(420)) # Affiche les 10 premières lignes bien alignées
    print("-" * 100)

    # --- SAUVEGARDE ---
    output_path2 = "jobs_keejobs_420.csv"
    df2.to_csv(output_path2, index=False, encoding='utf-8-sig')
    print(f"Fichier sauvegardé avec succès sous : {os.path.abspath(output_path2)}")
import pandas as pd
import numpy as np
import os

# --- CONFIGURATION POUR TOUT AFFICHER SUR UNE SEULE LIGNE ---
pd.set_option('display.max_columns', None)      # Affiche toutes les colonnes
pd.set_option('display.width', 2000)            # Largeur énorme pour éviter le retour à la ligne
pd.set_option('display.max_colwidth', 50)       # Limite un peu la largeur de chaque colonne pour que ça tienne
pd.set_option('display.expand_frame_repr', False) # Interdit à Pandas de couper le tableau en plusieurs blocs

# 1. Définition du chemin d'entrée
path3 = "jobs_tunijobs_420.csv"

if not os.path.exists(path3):
    print(f"ERREUR : Le fichier '{path3}' est introuvable dans {os.getcwd()}")
else:
    df3 = pd.read_csv(path3, encoding='utf-8')

    # --- NETTOYAGE ---
    df3.drop_duplicates(subset=['Lien'], inplace=True) if 'Lien' in df3.columns else df3.drop_duplicates(inplace=True)

    col_titre3 = 'Titre' if 'Titre' in df3.columns else 'Job Title'
    df3.dropna(subset=[col_titre3], inplace=True)

    df3.replace(['N/A', 'n/a', 'None'], np.nan, inplace=True)

    # Note: applymap est remplacé par map dans les versions récentes de Pandas
    df3 = df3.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

    # --- AFFICHAGE ---
    print(f"\nNettoyage terminé : {len(df3)} lignes conservées.")
    print("-" * 100)
    print(df3.head(150)) # Affiche les 10 premières lignes bien alignées
    print("-" * 100)

    # --- SAUVEGARDE ---
    output_path3 = "jobs_tunijobs_420.csv"
    df3.to_csv(output_path3, index=False, encoding='utf-8-sig')
    print(f"Fichier sauvegardé avec succès sous : {os.path.abspath(output_path3)}")
import pandas as pd
import numpy as np
import os

# --- CONFIGURATION POUR TOUT AFFICHER SUR UNE SEULE LIGNE ---
pd.set_option('display.max_columns', None)      # Affiche toutes les colonnes
pd.set_option('display.width', 2000)            # Largeur énorme pour éviter le retour à la ligne
pd.set_option('display.max_colwidth', 50)       # Limite un peu la largeur de chaque colonne pour que ça tienne
pd.set_option('display.expand_frame_repr', False) # Interdit à Pandas de couper le tableau en plusieurs blocs

# 1. Définition du chemin d'entrée
path4 = "jobs_tunisietravail_420.csv"

if not os.path.exists(path4):
    print(f"ERREUR : Le fichier '{path4}' est introuvable dans {os.getcwd()}")
else:
    df4 = pd.read_csv(path4, encoding='utf-8')

    # --- NETTOYAGE ---
    df4.drop_duplicates(subset=['Lien'], inplace=True) if 'Lien' in df4.columns else df4.drop_duplicates(inplace=True)

    col_titre4 = 'Titre' if 'Titre' in df4.columns else 'Job Title'
    df4.dropna(subset=[col_titre4], inplace=True)

    df4.replace(['N/A', 'n/a', 'None'], np.nan, inplace=True)

    # Note: applymap est remplacé par map dans les versions récentes de Pandas
    df4 = df4.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

    # --- AFFICHAGE ---
    print(f"\nNettoyage terminé : {len(df4)} lignes conservées.")
    print("-" * 100)
    print(df4.head(420)) # Affiche les 10 premières lignes bien alignées
    print("-" * 100)

    # --- SAUVEGARDE ---
    output_path4 = "jobs_tunisietravail_420.csv"
    df4.to_csv(output_path4, index=False, encoding='utf-8-sig')
    print(f"Fichier sauvegardé avec succès sous : {os.path.abspath(output_path4)}")

import pandas as pd
import numpy as np
import os

# ============================================================
# CONFIGURATION AFFICHAGE
# ============================================================
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_colwidth', 60)
pd.set_option('display.max_rows', 2000)
pd.set_option('display.expand_frame_repr', False)

# ============================================================
# FICHIERS A FUSIONNER
# Format : (fichier, source_label, limite_jobs)
# ============================================================
FICHIERS = [
    ("jobs_keejobs_420.csv",        "Keejob",         420),
    ("jobs_wuzzuf_420.csv",         "Wuzzuf",          420),
    ("jobs_tunisietravail_420.csv", "TunisieTravail",  420),
    ("jobs_tunijobs_420.csv",       "Tunijobs",        150),
]

OUTPUT_CSV = "jobs_all_1410.csv"

# Colonnes finales unifiees (union de toutes les sources)
# Wuzzuf ajoute : Skills, Education
COLONNES_CIBLES = [
    "Job_ID",
    "Titre",
    "Societe",
    "Description",
    "Skills",           # Wuzzuf uniquement (vide pour les autres)
    "Categories",
    "Annees_Experience",
    "Niveau_Experience",
    "Education",        # Wuzzuf uniquement (vide pour les autres)
    "Salaire",
    "Lieu",
    "Type_Contrat",
    "Mode_Travail",
    "Date_Publication",
    "Date_Relative",
    "Expire",
    "Source",
    "Lien",
]

NULL_VALS = ['N/A', 'n/a', 'NA', 'na', 'None', 'none', 'NaN', 'nan', '', ' ']

# ============================================================
# CHARGEMENT D'UN FICHIER SOURCE
# ============================================================
def charger_csv(path, source_label, limite):
    print(f"\n  -- {source_label} ({path}) --")

    if not os.path.exists(path):
        print(f"     ERREUR : fichier introuvable dans {os.getcwd()}")
        return pd.DataFrame()

    df = None
    for enc in ("utf-8-sig", "utf-8", "latin-1"):
        try:
            df = pd.read_csv(path, encoding=enc)
            if not df.empty:
                break
        except Exception:
            continue

    if df is None or df.empty:
        print(f"     ERREUR : fichier vide ou illisible")
        return pd.DataFrame()

    print(f"     Colonnes detectees       : {list(df.columns)}")
    print(f"     Lignes brutes            : {len(df):,}")

    # Strip espaces
    df = df.apply(lambda col: col.map(
        lambda x: x.strip() if isinstance(x, str) else x
    ))

    # Harmonisation colonne Titre
    col_titre = next(
        (c for c in ('Titre', 'Job Title', 'Title', 'titre') if c in df.columns), None
    )
    if col_titre and col_titre != 'Titre':
        df.rename(columns={col_titre: 'Titre'}, inplace=True)
        col_titre = 'Titre'

    # Drop lignes sans titre
    if col_titre:
        avant = len(df)
        df = df[df[col_titre].notna()]
        df = df[df[col_titre].astype(str).str.strip() != '']
        if avant - len(df) > 0:
            print(f"     Lignes sans titre supp.  : {avant - len(df):,}")

    # Dedoublonnage INTERNE sur Job_ID uniquement
    if 'Job_ID' in df.columns:
        avant = len(df)
        df.drop_duplicates(subset=['Job_ID'], keep='first', inplace=True)
        if avant - len(df) > 0:
            print(f"     Doublons Job_ID supprimes : {avant - len(df):,}")

    print(f"     Lignes apres nettoyage   : {len(df):,}")

    # Forcer la colonne Source
    df['Source'] = source_label

    # Ajouter les colonnes manquantes avec NaN
    for col in COLONNES_CIBLES:
        if col not in df.columns:
            df[col] = np.nan

    # Garder uniquement les colonnes cibles dans le bon ordre
    df = df[COLONNES_CIBLES].copy()

    # Limite
    disponible = len(df)
    df = df.head(limite)
    if disponible < limite:
        print(f"     ATTENTION : seulement {disponible} jobs dispo sur {limite} demandes")
        print(f"     -> Relancez le scraper {source_label} pour obtenir {limite} jobs")
    else:
        print(f"     OK : {len(df):,} jobs selectionnes")

    return df


# ============================================================
# EXECUTION PRINCIPALE
# ============================================================
if __name__ == "__main__":

    print("=" * 70)
    print("  FUSION DES CSV - TUNISIE JOB BOARDS")
    print(f"  Cible : 420+420+420+150 = 1 410 jobs")
    print(f"  Output: {OUTPUT_CSV}")
    print("=" * 70)

    frames = []
    total_cible = sum(limite for _, _, limite in FICHIERS)

    for path, label, limite in FICHIERS:
        df_src = charger_csv(path, label, limite)
        if not df_src.empty:
            frames.append(df_src)

    if not frames:
        print("\n  ERREUR : Aucun fichier source disponible.")
        exit(1)

    # Concatenation SANS dedoublonnage cross-sources
    df_all = pd.concat(frames, ignore_index=True)

    print(f"\n{'=' * 70}")
    print(f"  Lignes apres concat : {len(df_all):,} / {total_cible:,}")

    # Repartition par source
    print(f"\n  Repartition par source :")
    cibles = {label: limite for _, label, limite in FICHIERS}
    for src, cnt in df_all['Source'].value_counts().items():
        cible_src = cibles.get(src, 0)
        statut = "OK" if cnt >= cible_src else f"MANQUE {cible_src - cnt}"
        barre = '#' * (cnt // 20)
        print(f"    {src:<20} {cnt:>4} / {cible_src:<4}  {statut}  {barre}")

    # Remplacement valeurs nulles textuelles
    df_all.replace(NULL_VALS, np.nan, inplace=True)

    # Normalisation Date_Publication
    if 'Date_Publication' in df_all.columns:
        df_all['Date_Publication'] = pd.to_datetime(
            df_all['Date_Publication'], errors='coerce'
        ).dt.strftime('%Y-%m-%d')

    # Tri par source (ordre FICHIERS) puis date decroissante
    ordre_source = {label: i for i, (_, label, _) in enumerate(FICHIERS)}
    df_all['_ordre'] = df_all['Source'].map(ordre_source)
    df_all.sort_values(['_ordre', 'Date_Publication'],
                       ascending=[True, False], inplace=True)
    df_all.drop(columns=['_ordre'], inplace=True)
    df_all.reset_index(drop=True, inplace=True)

    # Sauvegarde
    df_all.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')

    # ══════════════════════════════════════════════════════════
    # RAPPORT FINAL
    # ══════════════════════════════════════════════════════════
    print(f"\n{'=' * 70}")
    print(f"  RAPPORT FINAL")
    print(f"{'=' * 70}")
    print(f"  Total jobs             : {len(df_all):,} / {total_cible:,}")
    print(f"  Colonnes               : {len(df_all.columns)} -> {list(df_all.columns)}")
    print(f"  Fichier                : {os.path.abspath(OUTPUT_CSV)}")

    print(f"\n  Completude des colonnes :")
    for col in df_all.columns:
        non_null = df_all[col].notna().sum()
        pct = non_null / len(df_all) * 100 if len(df_all) > 0 else 0
        barre = '#' * int(pct / 5) + '.' * (20 - int(pct / 5))
        print(f"    {col:<25} [{barre}] {pct:5.1f}%  ({non_null:,}/{len(df_all):,})")

    print(f"\n  Repartition par source (finale) :")
    for src, cnt in df_all['Source'].value_counts().items():
        cible_src = cibles.get(src, 0)
        statut = "OK" if cnt >= cible_src else f"MANQUE {cible_src - cnt}"
        barre = '#' * (cnt // 20)
        print(f"    {src:<20} {cnt:>4} / {cible_src:<4}  {statut}  {barre}")

    print(f"\n  Top 10 Type_Contrat :")
    for val, cnt in df_all['Type_Contrat'].value_counts(dropna=False).head(10).items():
        print(f"    {str(val):<35} {cnt:>4}")

    print(f"\n  Top 10 villes :")
    for val, cnt in df_all['Lieu'].value_counts(dropna=False).head(10).items():
        print(f"    {str(val):<35} {cnt:>4}")

    print(f"\n  Top 10 categories :")
    for val, cnt in df_all['Categories'].value_counts(dropna=False).head(10).items():
        print(f"    {str(val):<40} {cnt:>4}")

    # Affichage COMPLET - toutes les colonnes, tous les jobs
    print(f"\n{'=' * 70}")
    print(f"  LISTE COMPLETE - {len(df_all):,} JOBS (toutes colonnes)")
    print(f"{'=' * 70}")
    print(df_all.to_string(index=True))

    print(f"\n{'=' * 70}")
    if len(df_all) < total_cible:
        print(f"  ATTENTION : Il manque {total_cible - len(df_all):,} jobs.")
        print(f"  -> Wuzzuf et TunisieTravail n'ont que 150 jobs chacun.")
        print(f"  -> Relancez leurs scrapers avec MAX_JOBS = 420.")
    print(f"  Fusion terminee : {len(df_all):,} jobs -> {os.path.abspath(OUTPUT_CSV)}")
    print("=" * 70)

df_all.head()

cat_cols = df_all.select_dtypes(include='object').columns
num_cols = df_all.select_dtypes(include=['int64', 'float64']).columns

# Colonnes textuelles → "Unknown"
df_all[cat_cols] = df_all[cat_cols].fillna("Unknown")

# Colonnes numériques → 0 (ou moyenne si ML)
df_all[num_cols] = df_all[num_cols].fillna(0)

df_all.head(1410)