# -*- coding: utf-8 -*-
"""collaborative_filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1boj_gJ4Jd7JvMYACsH14lZg5SgW2KM-g

Import Python Libraries
"""

# Data processing
import pandas as pd
import numpy as np

# Visualization
import seaborn as sns

# Similarity
from sklearn.metrics.pairwise import cosine_similarity

"""Download And Read In Data"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Change directory
import os
os.chdir('/content/drive/MyDrive/contents/recommendation_system')

# Read in data
ratings = pd.read_csv('ml-latest-small/ratings.csv')
# Take a look at the data
ratings.head()

# Get the dataset information
ratings.info()

# Number of users
print('The ratings dataset has', ratings.userId.nunique(), 'unique users')
# Number of jobs
print('The ratings dataset has', ratings.jobId.nunique(), 'unique jobs')
# Number of ratings
print('The ratings dataset has', ratings.rating.nunique(), 'unique ratings')
# List of unique ratings
print('The unique ratings are', sorted(ratings.rating.unique()))

# Read in data
jobs = pd.read_csv('ml-latest-small/jobs.csv')
# Take a look at the data
jobs.head()

# Merge ratings and jobs datasets
df = pd.merge(ratings, jobs, on='jobId', how='inner')
# Take a look at the data
df.head()

"""Exploratory Data Analysis (EDA)"""

# Aggregate by job
agg_ratings = df.groupby('title').agg(
    mean_rating=('rating', 'mean'),
    number_of_ratings=('rating', 'count')
).reset_index()

# Keep jobs with more than 100 ratings
agg_ratings_GT100 = agg_ratings[agg_ratings['number_of_ratings'] > 100]
agg_ratings_GT100.info()

# Check popular jobs
agg_ratings_GT100.sort_values(by='number_of_ratings', ascending=False).head()

# Visualization
sns.jointplot(x='mean_rating', y='number_of_ratings', data=agg_ratings_GT100)

# Merge data
df_GT100 = pd.merge(df, agg_ratings_GT100[['title']], on='title', how='inner')
df_GT100.info()

# Number of users
print('The ratings dataset has', df_GT100.userId.nunique(), 'unique users')
# Number of jobs
print('The ratings dataset has', df_GT100.jobId.nunique(), 'unique jobs')
# Number of ratings
print('The ratings dataset has', df_GT100.rating.nunique(), 'unique ratings')
# List of unique ratings
print('The unique ratings are', sorted(df_GT100.rating.unique()))

"""Create User-Job Matrix"""

# Create user-item matrix
matrix = df_GT100.pivot_table(index='userId', columns='title', values='rating')
matrix.head()

"""Data Normalization"""

# Normalize user-item matrix
matrix_norm = matrix.subtract(matrix.mean(axis=1), axis='rows')
matrix_norm.head()

"""Identify Similar Users"""

# User similarity matrix using Pearson correlation
user_similarity = matrix_norm.T.corr()
user_similarity.head()

# Pick a user ID
picked_userId = 1

# Remove picked user ID from the candidate list
user_similarity.drop(index=picked_userId, inplace=True)
# Take a look at the data
user_similarity.head()

# Number of similar users
n = 10
# User similarity threshold
user_similarity_threshold = 0.3

# FIX: sort descending and limit to top n similar users
similar_users = (
    user_similarity[user_similarity[picked_userId] > user_similarity_threshold][picked_userId]
    .sort_values(ascending=False)
    .head(n)
)

# Print out top n similar users
print('The top', str(n), 'users similar to user', str(picked_userId), 'are:', similar_users)

"""Narrow Down Item Pool"""

# Jobs that target user has already rated
picked_userId_selected = matrix_norm[matrix_norm.index == picked_userId].dropna(axis=1, how='all')
picked_userId_selected

# Jobs that similar users rated — remove jobs none of them have rated
similar_user_jobs = matrix_norm[matrix_norm.index.isin(similar_users.index)].dropna(axis=1, how='all')
similar_user_jobs

# Remove jobs the target user has already rated
similar_user_jobs.drop(picked_userId_selected.columns, axis=1, inplace=True, errors='ignore')
similar_user_jobs

"""Recommend Items"""

# A dictionary to store item scores
item_score = {}

# Loop through items
for i in similar_user_jobs.columns:
    # Get the ratings for job i
    job_rating = similar_user_jobs[i]
    total = 0
    count = 0

    # Loop through similar users
    for u in similar_users.index:
        # If the job has a rating
        if pd.isna(job_rating[u]) == False:
            # Score = user similarity * job rating
            score = similar_users[u] * job_rating[u]
            total += score
            count += 1

    # Get the average score for the item
    if count > 0:
        item_score[i] = total / count

# Convert dictionary to pandas dataframe
item_score = pd.DataFrame(item_score.items(), columns=['title', 'job_score'])

# Sort the jobs by score
ranked_item_score = item_score.sort_values(by='job_score', ascending=False)

# Select top j jobs
j = 10
ranked_item_score.head(j)

"""Predict Scores"""

# Average rating for the picked user
avg_rating = matrix[matrix.index == picked_userId].T.mean()[picked_userId]
avg_rating

# FIX: correct format specifier :.2f
print(f'The average rating for user {picked_userId} is {avg_rating:.2f}')

# Calculate the predicted rating
ranked_item_score['job_predicted_rating'] = ranked_item_score['job_score'] + avg_rating

# Take a look at the data
ranked_item_score.head(j)
